Repository canonical/dex-auth-operator, pull requests merged in 2023-08, with the labels that each got.

#144 build: update requirements*.in and their corresponding .txt files to match standards
  charmcraft.yaml
  config.yaml
  metadata.yaml
  requirements-fmt.txt
  requirements-integration.txt
  requirements-lint.txt
  requirements-unit.in
  requirements-unit.txt
  requirements.in
  requirements.txt
  src/charm.py
  tests/integration/test_charm.py
  tests/integration/test_upgrade_charm.py
  tests/unit/test_charm.py
  tox.ini
Labels: Libraries: Out of sync

#149 feat: add `enablePasswordDB` charm configuration option to enable/disable static password login
  config.yaml
  src/charm.py
  tests/unit/test_charm.py
Labels: Libraries: Out of sync

#148 feat: Remove apt-install from Dex Charm
  src/charm.py
Labels: Libraries: Out of sync

#156 requirements: Pin selenium version to 4.10.x
  requirements-integration.in
Labels: Libraries: Out of sync

#152 build: bump grafana, observability and prometheus libs
  lib/charms/grafana_k8s/v0/grafana_dashboard.py
  lib/charms/observability_libs/v0/juju_topology.py
  lib/charms/prometheus_k8s/v0/prometheus_scrape.py
Labels: Libraries: OK

#153 feat: add `enablePasswordDB` charm configuration option to enable/disable static password login (#149)
  charmcraft.yaml
  config.yaml
  src/charm.py
  tests/unit/test_charm.py
Labels: Libraries: Out of sync, backport

#150 feat: upgrade dex-auth from 2.31.2 to 2.36.0
  metadata.yaml
Labels: Libraries: OK
